"""add_trend_analysis_table

Revision ID: c64072744744
Revises: 6d1e248a486d
Create Date: 2025-10-10 14:18:28.233039+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64072744744'
down_revision = '6d1e248a486d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('view_growth_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('watch_growth_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('view_7day_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('watch_7day_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_analysis_analysis_date'), 'trend_analysis', ['analysis_date'], unique=False)
    op.create_index('ix_trend_analysis_date_score', 'trend_analysis', ['analysis_date', 'trend_score'], unique=False)
    op.create_index('ix_trend_analysis_date_trending', 'trend_analysis', ['analysis_date', 'is_trending'], unique=False)
    op.create_index(op.f('ix_trend_analysis_is_trending'), 'trend_analysis', ['is_trending'], unique=False)
    op.create_index('ix_trend_analysis_listing_date', 'trend_analysis', ['listing_id', 'analysis_date'], unique=True)
    op.create_index(op.f('ix_trend_analysis_listing_id'), 'trend_analysis', ['listing_id'], unique=False)
    op.create_index(op.f('ix_trend_analysis_rank'), 'trend_analysis', ['rank'], unique=False)
    op.create_index(op.f('ix_trend_analysis_trend_score'), 'trend_analysis', ['trend_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_analysis_trend_score'), table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_rank'), table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_listing_id'), table_name='trend_analysis')
    op.drop_index('ix_trend_analysis_listing_date', table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_is_trending'), table_name='trend_analysis')
    op.drop_index('ix_trend_analysis_date_trending', table_name='trend_analysis')
    op.drop_index('ix_trend_analysis_date_score', table_name='trend_analysis')
    op.drop_index(op.f('ix_trend_analysis_analysis_date'), table_name='trend_analysis')
    op.drop_table('trend_analysis')
    # ### end Alembic commands ###
