"""add_listings_and_daily_metrics_tables

Revision ID: 6d1e248a486d
Revises: 196c5f590a3f
Create Date: 2025-10-10 11:50:41.973412+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d1e248a486d'
down_revision = '196c5f590a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('item_specifics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listing_type', sa.String(length=50), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['ebay_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_account_active', 'listings', ['account_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_listings_account_id'), 'listings', ['account_id'], unique=False)
    op.create_index('ix_listings_account_item', 'listings', ['account_id', 'item_id'], unique=True)
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_item_id'), 'listings', ['item_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_metrics_date', 'daily_metrics', ['recorded_date'], unique=False)
    op.create_index('ix_daily_metrics_listing_date', 'daily_metrics', ['listing_id', 'recorded_date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_listing_id'), 'daily_metrics', ['listing_id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_recorded_date'), 'daily_metrics', ['recorded_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metrics_recorded_date'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_listing_id'), table_name='daily_metrics')
    op.drop_index('ix_daily_metrics_listing_date', table_name='daily_metrics')
    op.drop_index('ix_daily_metrics_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_listings_item_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_index('ix_listings_account_item', table_name='listings')
    op.drop_index(op.f('ix_listings_account_id'), table_name='listings')
    op.drop_index('ix_listings_account_active', table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
