"""add_analytics_metrics_table

Revision ID: a23f24b9674c
Revises: c64072744744
Create Date: 2025-10-10 14:59:13.350401+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23f24b9674c'
down_revision = 'c64072744744'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('click_through_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listing_impression', sa.Integer(), nullable=False),
    sa.Column('listing_views', sa.Integer(), nullable=False),
    sa.Column('sales_conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_metrics_listing_date', 'analytics_metrics', ['listing_id', 'recorded_date'], unique=True)
    op.create_index(op.f('ix_analytics_metrics_listing_id'), 'analytics_metrics', ['listing_id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_recorded_date'), 'analytics_metrics', ['recorded_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_metrics_recorded_date'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_listing_id'), table_name='analytics_metrics')
    op.drop_index('ix_analytics_metrics_listing_date', table_name='analytics_metrics')
    op.drop_table('analytics_metrics')
    # ### end Alembic commands ###
